name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Check formatting with black
        uses: psf/black@stable
      - uses: isort/isort-action@master
        with:
          requirementsFiles: "dev-requirements.txt"
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint with flake8
        run: flake8 --count --statistics
      - name: Static analysis with mypy
        run: mypy
      - name: Unittests with pytest
        run: pytest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build docker container
        uses: docker/build-push-action@v3
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true
      - name: Scan docker image
        uses: anchore/scan-action@v3
        with:
          image: localbuild/testimage:latest
          fail-build: false
          output-format: table
